name: I Fell in Love with an Asexual
favicon: null
layout_spectrum: 0.87989
typography_spectrum: 0.9163171141408384
title: I Fell in Love with an Asexual but I Still Love Sex
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e3262a'
    - '#000000'
    - '#5b5b5b'
    - '#e97074'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.7743221479468048
purpose: []
